project:
  type: website
  lang: pt-BR

website:
  page-navigation: true
  title: "Introdução ao GNU/Linux"
  site-url: "https://paulobarros.github.io/introducao-ao-linux"
  repo-url: "https://github.com/paulobarros/introducao-ao-linux"
  repo-actions: [issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "![Caption](images/FrogPB.png)    &copy; CC-By Paulo Barros, 2022"
    
  sidebar:
    logo: "images/LogoTux.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://paulobarros.com.br
        text: "paulobarros.com.br"
      - icon: github
        href: https://github.com/paulobarros/introducao-ao-linux
        text: "Introdução ao GNU/Linux"
      - icon: twitter
        href: https://twitter.com/pbarrosjr
        text: "Paulo Barros Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Apresentação
      - href: wsl.qmd
        text: Instalando o WSL
      - href: linux.qmd
        text: O que é o Linux?
      - section: lfs/index.qmd
        contents: 
          - lfs/terminal.qmd

format:
  html:
    theme:
      light: [yeti, pbstyle.scss]
      dark: [darkly, pbstyle.scss]
    code-copy: true
    code-overflow: wrap
    code-block-bg: "#1A3434"
    code-block-border-left: "#FFF0B0"
    code-line-numbers: true
    highlight-style: dracula
    toc: true


