---
title: Instalando o Windows Subsystem for Linux (WSL)
---

O WSL é uma ferramenta da Microsoft que permite a instalação de uma distribuição Linux sem a necessidade de _dual-boot_. Desta maneira o usuário tem acesso a ferramentas do Linux como Bash, integradas ao ambiente de ferramentas do Windows utilizando o PowerShell. A documentação oficial do WSL encontra-se [neste link](https://docs.microsoft.com/en-us/windows/wsl/install).

## Pré-requisitos {#precheck}

::: {.callout-note}
## Importante

Para utilizar a instalação do WSL via terminal de comando você precisa ter o **Windows 10** versão 2004 ou superior (_Build_ 19041 ou superior) ou **Windows 11**.

Para checar qual a sua versão do Windows e número da _build_, pressione `Windows` + `R`, digite `winver` e pressione `OK`. 

Se possui uma versão mais antiga do Windows e quiser instalar o WSL, [aqui tem um tutorial passo-a-passo para versões mais antigas.](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
:::


## Instalação

Para instalar o WSL basta abrir o PowerShell ou o terminal de comando padrão do Windows em modo administrador e rodar o comando:

```{r}
#| eval: false
wsl --install
```

Esse comando faz o download dos requerimentos necessários e do kernel do Linux, configura o WSL 2 como padrão e instala uma distribuição Linux para você, que por padrão é a Ubuntu. A primeira vez que você iniciar sua instalação Linux, o terminal irar abrir e você deverá aguardar alguns minutos para que os arquivos sejam preaprados, as próximas inicializações serão mais rápidas.

### Configurando informações do seu usuário

Uma vez instalado o WSL, você precisará criar uma conta de usuário e senha para distribuição instalada. Evite nomes de usuário extensos e com caracteres especiais, acentuação ou espaços. A senha também deve ser algo fácil de lembrar pois será constantemente requisitada na hora de rodar comandos no terminal.

